# Generated by Django 4.0.5 on 2022-06-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oferty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korepetytor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=60)),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Korepetytor',
                'verbose_name_plural': 'Korepetytorzy',
            },
        ),
        migrations.AlterModelOptions(
            name='oferty',
            options={'verbose_name': 'Oferta', 'verbose_name_plural': 'Oferty'},
        ),
    ]
