# Generated by Django 4.0.5 on 2022-06-03 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Oferty', '0002_korepetytor_alter_oferty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferty',
            name='korepetytor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Oferty.korepetytor'),
        ),
        migrations.AlterField(
            model_name='oferty',
            name='nazwa',
            field=models.CharField(max_length=60),
        ),
    ]
