# Generated by Django 4.0.5 on 2022-06-03 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Oferty', '0003_oferty_korepetytor_alter_oferty_nazwa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poziom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='oferty',
            name='poziom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Oferty.poziom'),
        ),
    ]
