# Generated by Django 4.0.5 on 2022-06-03 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Oferty', '0004_poziom_oferty_poziom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poziom',
            options={'verbose_name': 'Poziom', 'verbose_name_plural': 'Poziomy'},
        ),
        migrations.AddField(
            model_name='poziom',
            name='nazwa',
            field=models.CharField(default=60, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oferty',
            name='poziom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Oferty.poziom'),
        ),
    ]
