# Generated by Django 4.0.5 on 2022-06-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oferty', '0005_alter_poziom_options_poziom_nazwa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poziom',
            name='nazwa',
            field=models.CharField(max_length=60),
        ),
    ]
